on: push
name: Test Workflow 1

jobs:
  First-Job:
    runs-on: ubuntu-latest
    steps:
    - name: Make File
      run: |
        echo Making File
        touch myfile.txt
    - name: See Files
      run: ls -a
    - name: Get PWD
      run: |
        CUR_DIR=$(pwd)
        echo Current Directory is $CUR_DIR