on: push
name: Test Workflow 1

jobs:
  First-Job:
    runs-on: ubuntu-latest
    steps:
    - name: Get Repo
      uses: actions/checkout@v2

    - name: Make File
      run: |
        echo Making File
        touch myfile.txt

    - name: See Files
      run: ls -a

    - name: Get PWD
      run: |
        CUR_DIR=$(pwd)
        echo Current Directory is $CUR_DIR
    
    - name: Run Container
      run: docker run --rm -v $(pwd):/usr/src/myapp -w /usr/src/myapp python:latest python app.py